# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

# limit = 4000000
# a = 1
# b = 0
# temp = 0
# while a < limit:
#     a = a+b
#     b = a
#     if a % 2 == 0:
#         temp += a
# print temp


a, b, s = 1, 0, 0
while a < 4000000:
    a, b = a+b, a
    if a % 2 == 0:
        s += a
print s
